### ISSUE TITLE
[ERROR] ModuleNotFoundError(No module named 'datalad_metalad.extractors.studyminimeta') (ModuleNotFoundError)

### ISSUE THREAD

**Issue by jsheunis** [jsheunis/fairly-big-catalog-workflow#6]
Occurring when running

```
 local/local_run_main.sh $SUPER_PATH $OUTDIR $CATALOGDIR
```

example output:

```
---
15) Extract+translate+add metadata for subdataset: original/3T_multiresolution_fmri
---
[INFO] Start core metadata extraction from Dataset(/Users/jsheunis/Documents/psyinf/Data/studyforrest-data/original/3T_multiresolution_fmri)
[INFO] Extracted core metadata from /Users/jsheunis/Documents/psyinf/Data/studyforrest-data/original/3T_multiresolution_fmri
[INFO] Finished core metadata extraction from Dataset(/Users/jsheunis/Documents/psyinf/Data/studyforrest-data/original/3T_multiresolution_fmri)
[INFO] Start bids_dataset metadata extraction from /Users/jsheunis/Documents/psyinf/Data/studyforrest-data/original/3T_multiresolution_fmri
[INFO] Finished bids_dataset metadata extraction from /Users/jsheunis/Documents/psyinf/Data/studyforrest-data/original/3T_multiresolution_fmri
[ERROR] ModuleNotFoundError(No module named 'datalad_metalad.extractors.studyminimeta') (ModuleNotFoundError)
Translating line 1:
Not metadata, skipping line: subdataset(ok): code/mridefacer (dataset)
Translating line 2:
Not metadata, skipping line: subdataset(ok): sourcedata (dataset)
Translating line 3:
jq: error (at <stdin>:84): null (null) cannot be matched, as it is not a string
Translating line 4:
jq: error (at <stdin>:105): Cannot iterate over null (null)
jq: error: doi/0 is not defined at <top-level>, line 1:
doi
jq: 1 compile error
[WARNING] Node instance already has an attribute 'type'. Overwriting attribute value with non-zero/null content.To prevent overwriting, set 'overwrite' argument to False
[WARNING] Node instance already has an attribute 'dataset_id'. Overwriting attribute value with non-zero/null content.To prevent overwriting, set 'overwrite' argument to False
[WARNING] Node instance already has an attribute 'dataset_version'. Overwriting attribute value with non-zero/null content.To prevent overwriting, set 'overwrite' argument to False
[ERROR] JSONDecodeError(Expecting value: line 1 column 1 (char 0)) (JSONDecodeError)
```

_Note: this examples contains other separate errors as well, not handled here._

Looks like `metalad_studyminimeta` is somehow not  loaded. In the output of `datalad wtf` we see:

```
- metalad_studyminimeta (datalad-metalad 0.3.1+10.g9c6972a):
    - distribution: datalad-metalad 0.3.1+10.g9c6972a
    - load_error: ModuleNotFoundError(No module named 'datalad_metalad.extractors.studyminimeta')
    - module: datalad_metalad.extractors.studyminimeta.main
```

**Comment by jsheunis** [comment]
Could be a result of the module being `datalad_metalad.extractors.studyminimeta.main` and not `datalad_metalad.extractors.studyminimeta`

Also replicated as follows:

```
>> datalad -f json_pp meta-extract -d ../Data/studyforrest-data/original/3T_multiresolution_fmri metalad_studyminimeta

[ERROR  ] ModuleNotFoundError(No module named 'datalad_metalad.extractors.studyminimeta') (ModuleNotFoundError)
```

**Comment by jsheunis** [comment]
With debugger:

```
>> datalad --dbg meta-extract -d . metalad_studyminimeta

Traceback (most recent call last):
  File "/Users/jsheunis/opt/miniconda3/envs/fairlybigcat/bin/datalad", line 8, in <module>
    sys.exit(main())
  File "/Users/jsheunis/opt/miniconda3/envs/fairlybigcat/lib/python3.9/site-packages/datalad/cmdline/main.py", line 211, in main
    ret = cmdlineargs.func(cmdlineargs)
  File "/Users/jsheunis/opt/miniconda3/envs/fairlybigcat/lib/python3.9/site-packages/datalad/interface/base.py", line 786, in call_from_parser
    ret = list(ret)
  File "/Users/jsheunis/opt/miniconda3/envs/fairlybigcat/lib/python3.9/site-packages/datalad/interface/utils.py", line 396, in generator_func
    for r in _process_results(
  File "/Users/jsheunis/opt/miniconda3/envs/fairlybigcat/lib/python3.9/site-packages/datalad/interface/utils.py", line 579, in _process_results
    for res in results:
  File "/Users/jsheunis/opt/miniconda3/envs/fairlybigcat/lib/python3.9/site-packages/datalad_metalad/extract.py", line 247, in __call__
    extractor_class = get_extractor_class(extractor_name)
  File "/Users/jsheunis/opt/miniconda3/envs/fairlybigcat/lib/python3.9/site-packages/datalad_metalad/extract.py", line 465, in get_extractor_class
    return entry_point.load()
  File "/Users/jsheunis/opt/miniconda3/envs/fairlybigcat/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2450, in load
    return self.resolve()
  File "/Users/jsheunis/opt/miniconda3/envs/fairlybigcat/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'datalad_metalad.extractors.studyminimeta'

> /Users/jsheunis/opt/miniconda3/envs/fairlybigcat/lib/python3.9/site-packages/pkg_resources/__init__.py(2456)resolve()
-> module = __import__(self.module_name, fromlist=['__name__'], level=0)
```

**Comment by jsheunis** [comment]
So it looks like the `EntryPoint.resolve()` method of the `pkg_resources` package doesn't take arguments, and it provides specific arguments for `__import__`:

```
module = __import__(self.module_name, fromlist=['__name__'], level=0)
```

Therefore, it doesn't know that it should import `main` from datalad_metalad.extractors.studyminimeta rather than datalad_metalad.extractors.studyminimeta itself.

@christian-monch do you have input on this?

**Comment by jsheunis** [comment]
Fixed in https://github.com/datalad/datalad-metalad/pull/248
